/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sanmatiasresort;

import Clases.Conexion;
import Clases.Utilidades;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
public class cotizacion extends javax.swing.JFrame {
Conexion cn = new Conexion();
iniciosesion is= new iniciosesion();
    Connection c = cn.conectar();
    PreparedStatement ps;
    ResultSet rs;
    Statement st;
    DefaultTableModel dtm;
    Utilidades util = new Utilidades();
    String codigo; 
    Double Precio = 100.00;
    float precio_extra; 
    int dias;
    int cantidadnoches;
    int cod;
    int cantidadP;
    int Codigo;
    float isv;
    float personas, subtotal, Isv;
    float precio_cabaña;
    
    public cotizacion() {
         initComponents();
        
       lblfechacotizacion.setText(util.FechaActual());
        this.setLocationRelativeTo(null);
        mostrarTabla();
        this.cmbcliente.setModel(cn.obtenerCliente());
        this.cmbcabana.setModel(cn.obtenerCabañas());
    }
    public void limpiardatos(){
        
        cmbcliente.setSelectedIndex(0);
        cmbcabana.setSelectedIndex(0);
        txtcantidadpersonascotizacion.setText(null);
        txtcantidadnochescotizacion.setText(null);
        txttotal.setText(null);
        txtisv.setText(null);
        txtSubtotal.setText(null);
    }
      
    public void mostrarTabla(){
         DefaultTableModel modelo = new DefaultTableModel();
        rs = cn.LlenarTabla("SELECT * FROM sanmatiasresort.cotizaciones as A\n" +
                        "join detalle_cotizaciones as B on A.codigo_cotizacion=B.codigo_cotizacion");
       
        modelo.setColumnIdentifiers(new Object[]{
            "Código",
            "Codigo Empleado",
            "Codigo Cliente",
            "Cabaña",
            "cantidad personas",
            "costo extra",
          
            "cantidad_noches"
            
            
            
        });
        try{
            while(rs.next()){
                modelo.addRow(new Object[]{
                    rs.getString("codigo_cotizacion"),
                    rs.getString("codigo_empleado"),
                    rs.getString("codigo_cliente"),
                    rs.getInt("codigo_cabaña"),
                    rs.getInt("cantidad_personas"),
                    rs.getInt("costo_extra"),
                    
                    rs.getInt("cantidad_noches")
                   // rs.getString("cantidad_noches")
                });
            }
            tablacotizacion.setModel(modelo);
        }catch(SQLException e){
            System.out.println(e);
        }
    }
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
        public static String NOMBRE="";
    public static String CABAÑA="";
    public static String PRECIO="";
    public static String CAPACIDAD="";
    public static String VISITANTES="";
    public static String NOCHES="";
    ///TOTALES
    public static String CANTIDAD="";
    public static String EXTRA="";
    public static String CANT_NOCHES="";
    public static String PRECIOEXTRA="";
    public static String SUBTOTAL="";
    public static String ISV="";
    public static String TOTAL="";
     
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        panelprincipal = new javax.swing.JPanel();
        lblcotizacion = new javax.swing.JLabel();
        lbldnicliente = new javax.swing.JLabel();
        lblcabana = new javax.swing.JLabel();
        btnvolvercotizacion = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablacotizacion = new javax.swing.JTable();
        lblcantidadpersonas = new javax.swing.JLabel();
        txtcantidadpersonascotizacion = new javax.swing.JTextField();
        lbldiallegada = new javax.swing.JLabel();
        txtcantidadnochescotizacion = new javax.swing.JTextField();
        cmbcabana = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        lblcorreoelectronico3 = new javax.swing.JLabel();
        lblcorreoelectronico4 = new javax.swing.JLabel();
        lblcorreoelectronico5 = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        lblcorreoelectronico8 = new javax.swing.JLabel();
        txtisv = new javax.swing.JTextField();
        lblcorreoelectronico9 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        lblcorreoelectronico10 = new javax.swing.JLabel();
        lblfechacotizacion = new javax.swing.JLabel();
        btnagregarcotizacion = new javax.swing.JButton();
        btngenerarcotizacion = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbcliente = new javax.swing.JComboBox<>();

        jButton5.setText("Reservación");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(33, 126, 194));

        panelprincipal.setBackground(new java.awt.Color(33, 126, 194));
        panelprincipal.setForeground(new java.awt.Color(33, 126, 194));

        lblcotizacion.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblcotizacion.setForeground(new java.awt.Color(255, 255, 255));
        lblcotizacion.setText("COTIZACIÓN");

        lbldnicliente.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbldnicliente.setForeground(new java.awt.Color(255, 255, 255));
        lbldnicliente.setText("DNI Cliente");

        lblcabana.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblcabana.setForeground(new java.awt.Color(255, 255, 255));
        lblcabana.setText("Cabaña");

        btnvolvercotizacion.setBackground(new java.awt.Color(230, 203, 1));
        btnvolvercotizacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnvolvercotizacion.setForeground(new java.awt.Color(255, 255, 255));
        btnvolvercotizacion.setText("Volver");
        btnvolvercotizacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnvolvercotizacionMouseClicked(evt);
            }
        });
        btnvolvercotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolvercotizacionActionPerformed(evt);
            }
        });

        tablacotizacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(tablacotizacion);

        lblcantidadpersonas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblcantidadpersonas.setForeground(new java.awt.Color(255, 255, 255));
        lblcantidadpersonas.setText("Cantidad de Personas");

        lbldiallegada.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbldiallegada.setForeground(new java.awt.Color(255, 255, 255));
        lbldiallegada.setText("Cantidad de Días");

        cmbcabana.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblcorreoelectronico3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblcorreoelectronico3.setText("ISV");

        lblcorreoelectronico4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblcorreoelectronico4.setText("Total");

        lblcorreoelectronico5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblcorreoelectronico5.setText("Subtotal");

        txtSubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubtotalActionPerformed(evt);
            }
        });

        lblcorreoelectronico8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblcorreoelectronico8.setText("Lps");

        lblcorreoelectronico9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblcorreoelectronico9.setText("Lps");

        lblcorreoelectronico10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblcorreoelectronico10.setText("Lps");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblcorreoelectronico5)
                    .addComponent(lblcorreoelectronico4)
                    .addComponent(lblcorreoelectronico3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblcorreoelectronico10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblcorreoelectronico9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtisv, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblcorreoelectronico8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblcorreoelectronico8)
                                        .addComponent(txtSubtotal))
                                    .addGap(39, 39, 39))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblcorreoelectronico9)
                                    .addComponent(txtisv, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(6, 6, 6))
                        .addComponent(lblcorreoelectronico10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblcorreoelectronico5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblcorreoelectronico3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblcorreoelectronico4)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        lblfechacotizacion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblfechacotizacion.setForeground(new java.awt.Color(255, 255, 255));
        lblfechacotizacion.setText("Fecha/Hora");

        btnagregarcotizacion.setBackground(new java.awt.Color(30, 150, 56));
        btnagregarcotizacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnagregarcotizacion.setForeground(new java.awt.Color(255, 255, 255));
        btnagregarcotizacion.setText("Agregar");
        btnagregarcotizacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnagregarcotizacionMouseClicked(evt);
            }
        });
        btnagregarcotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarcotizacionActionPerformed(evt);
            }
        });

        btngenerarcotizacion.setBackground(new java.awt.Color(62, 61, 86));
        btngenerarcotizacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btngenerarcotizacion.setForeground(new java.awt.Color(255, 255, 255));
        btngenerarcotizacion.setText("Generar Cotización");
        btngenerarcotizacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btngenerarcotizacionMouseClicked(evt);
            }
        });
        btngenerarcotizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngenerarcotizacionActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(32, 126, 193));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logocirculo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        cmbcliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelprincipalLayout = new javax.swing.GroupLayout(panelprincipal);
        panelprincipal.setLayout(panelprincipalLayout);
        panelprincipalLayout.setHorizontalGroup(
            panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelprincipalLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelprincipalLayout.createSequentialGroup()
                        .addGroup(panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelprincipalLayout.createSequentialGroup()
                                .addGroup(panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cmbcliente, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblcantidadpersonas, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcantidadpersonascotizacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                                    .addComponent(cmbcabana, javax.swing.GroupLayout.Alignment.LEADING, 0, 256, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelprincipalLayout.createSequentialGroup()
                                .addGroup(panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcantidadnochescotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbldnicliente)
                                    .addComponent(lblcotizacion)
                                    .addComponent(lblcabana)
                                    .addComponent(lbldiallegada))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(39, 39, 39)
                        .addComponent(btnagregarcotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(259, 259, 259)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelprincipalLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnvolvercotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btngenerarcotizacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelprincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblfechacotizacion)
                .addGap(206, 206, 206))
        );
        panelprincipalLayout.setVerticalGroup(
            panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelprincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblfechacotizacion)
                .addGap(3, 3, 3)
                .addGroup(panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelprincipalLayout.createSequentialGroup()
                        .addComponent(lblcotizacion)
                        .addGap(7, 7, 7)
                        .addComponent(lbldnicliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnagregarcotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblcabana)
                        .addGap(18, 18, 18)
                        .addComponent(cmbcabana, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(lblcantidadpersonas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcantidadpersonascotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lbldiallegada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtcantidadnochescotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelprincipalLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelprincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btngenerarcotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnvolvercotizacion)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnvolvercotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolvercotizacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnvolvercotizacionActionPerformed

    private void btnagregarcotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarcotizacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnagregarcotizacionActionPerformed

    private void btngenerarcotizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngenerarcotizacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btngenerarcotizacionActionPerformed

    private void txtSubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubtotalActionPerformed

    private void btnvolvercotizacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnvolvercotizacionMouseClicked
        menu mnt = new menu();
        mnt.setVisible(true);
        this.setVisible(false);



        // TODO add your handling code here:
    }//GEN-LAST:event_btnvolvercotizacionMouseClicked
 public double Pagos(int cantidadp, double preciocabaña){
        int resta;
        if(Integer.parseInt(txtcantidadpersonascotizacion.getText().toString())<=cantidadp){
            personas = 0;
            precio_extra=0;
        } else {
            resta = Integer.parseInt(txtcantidadpersonascotizacion.getText().toString())-cantidadp;
            personas= (float) (resta * Precio);
            
        }
        
        subtotal = (float) (precio_cabaña + personas + CantidadNoches());
        Isv = (float) (subtotal * 0.15);
        return subtotal+Isv;
    }
    
    public double CantidadNoches(){
        double PrecioNoche; 
        if (cantidadnoches == 1){
            PrecioNoche =0;
        }else{
            
            PrecioNoche = cantidadnoches * precio_cabaña; 
        }
        return PrecioNoche; 
    }
   int codigo_cabaña=0;
    
    private void btnagregarcotizacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnagregarcotizacionMouseClicked
    String strRespuesta = "";
    
       try{
           ps = c.prepareStatement("select precio_cabaña,codigo_cabaña from cabañas where descripcion_cabaña = ?");
           ps.setString(1, cmbcabana.getSelectedItem().toString());
           rs = ps.executeQuery();
           while(rs.next()){
              precio_cabaña = (float) rs.getDouble("precio_cabaña");
              codigo_cabaña=rs.getInt("codigo_cabaña");
           }
           
           ps= c.prepareStatement("select capacidad_cabaña from cabañas where codigo_cabaña=?");
           ps.setInt(1, codigo_cabaña);
           rs = ps.executeQuery();
           while(rs.next()){
               cantidadP=rs.getInt("capacidad_cabaña");
           }
          
             strRespuesta = util.strPreguntaSiNo("¿Desea Ingresar la cotizacion?");
                  if (strRespuesta=="Si"){
                    
         
      JOptionPane.showMessageDialog(null,"Registro de datos exitosa");
           
            cantidadnoches=Integer.parseInt(txtcantidadnochescotizacion.getText());
            
           txttotal.setText(String.valueOf(Pagos(cantidadP,precio_cabaña)));
           txtSubtotal.setText(String.valueOf(subtotal));
           txtisv.setText(String.valueOf(Isv));
            
            ps=c.prepareStatement("call sanmatiasresort.INSERT_COTIZACION(?,?,?,?,?,?,?);");
            ps.setInt(1, is.empleado);
            ps.setInt(2, cmbcliente.getSelectedIndex());
            ps.setInt(3, codigo_cabaña);
            ps.setInt(4,cantidadP);
            ps.setFloat(5,personas);
            ps.setInt(6,cantidadnoches);
            ps.setFloat(7,precio_cabaña);
            ps.executeUpdate();
            mostrarTabla();
                 
            
            JOptionPane.showMessageDialog(null, "Registro Ingresado");
                  }
                  else{
                JOptionPane.showMessageDialog(null,"Registro No Ingresado");
           }
                
       } catch(SQLException ex) {
            Logger.getLogger(cotizacion.class.getName()).log(Level.SEVERE, null, ex);
       }

    }//GEN-LAST:event_btnagregarcotizacionMouseClicked

    private void btngenerarcotizacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btngenerarcotizacionMouseClicked
 NOMBRE=cmbcliente.getSelectedItem().toString();
        CABAÑA=cmbcabana.getSelectedItem().toString();
        PRECIO=Double.toString(precio_cabaña);
        CAPACIDAD=Integer.toString(cantidadP);
        CANTIDAD=txtcantidadpersonascotizacion.getText();
        PRECIOEXTRA=Double.toString(personas);
        CANT_NOCHES=txtcantidadnochescotizacion.getText();
        SUBTOTAL=txtSubtotal.getText();
        ISV=txtisv.getText();
        TOTAL=txttotal.getText(); 
        Cotizar cot = new Cotizar();
        cot.setVisible(true);
        this.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_btngenerarcotizacionMouseClicked


private void tablacotizacionMouseClicked(java.awt.event.MouseEvent evt) {                                             
        int contadorcolumna = tablacotizacion.getRowCount();
        if(contadorcolumna == -1){
            JOptionPane.showMessageDialog(null, "Ingrese datos para poder visualizarlos");
        }else{
            btnagregarcotizacion.setEnabled(false);
           
            
        
            int seleccion = tablacotizacion.rowAtPoint(evt.getPoint());
            codigo=String.valueOf(tablacotizacion.getValueAt(seleccion, 0));
            cmbcliente.setSelectedItem(tablacotizacion.getValueAt(tablacotizacion.getSelectedRow(),2).toString());
            }
        
        
    }   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cotizacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregarcotizacion;
    private javax.swing.JButton btngenerarcotizacion;
    private javax.swing.JButton btnvolvercotizacion;
    private javax.swing.JComboBox<String> cmbcabana;
    private javax.swing.JComboBox<String> cmbcliente;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcabana;
    private javax.swing.JLabel lblcantidadpersonas;
    private javax.swing.JLabel lblcorreoelectronico10;
    private javax.swing.JLabel lblcorreoelectronico3;
    private javax.swing.JLabel lblcorreoelectronico4;
    private javax.swing.JLabel lblcorreoelectronico5;
    private javax.swing.JLabel lblcorreoelectronico8;
    private javax.swing.JLabel lblcorreoelectronico9;
    private javax.swing.JLabel lblcotizacion;
    private javax.swing.JLabel lbldiallegada;
    private javax.swing.JLabel lbldnicliente;
    private javax.swing.JLabel lblfechacotizacion;
    private javax.swing.JPanel panelprincipal;
    private javax.swing.JTable tablacotizacion;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtcantidadnochescotizacion;
    private javax.swing.JTextField txtcantidadpersonascotizacion;
    private javax.swing.JTextField txtisv;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
