/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sanmatiasresort;

import Clases.Conexion;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author mcsfl
 */
public class Facturita extends javax.swing.JFrame implements Printable{
    
    Conexion cn = new Conexion();
   Connection c= cn.conectar();
   ResultSet rs; 
   PreparedStatement st;
   
   
  

    public Facturita() {
        initComponents();
        
        FacturacionR r= new FacturacionR();
         
        String impuesto=r.SUBTOTAL;
        Double isv; 
        isv=Double.parseDouble(impuesto)*0.15;
        String ISV;
        ISV=String.valueOf(isv);
               
         
         
        lblID.setText(r.ID);
        lblCabaña.setText(r.CABANA);
        lblNombre.setText(r.NOMBRE);
        lblCantidad.setText(r.CANTIDAD);
        lblPrecio.setText(r.PRECIO);
        lblSubtotal.setText(r.SUBTOTAL);
        lblTotal.setText(r.TOTAL);
        lblEntrada.setText(r.ENTRADA);
        lblSalida.setText(r.SALIDA);
        lblVisitantes.setText(r.VISITANTES);
        lblRecargo.setText(r.RECARGO);
        lblISV.setText(ISV);
        
        
        fecha_emision.setText(currentDate());
        
         Factura1.setText(r.Factura);
        
        
       
        this.setLocationRelativeTo(null);
        ImageIcon imagen6 = new ImageIcon("src/Imagenes/flecha-hacia-atras.png");
       Icon icono6 = new ImageIcon(imagen6.getImage().getScaledInstance( lblAtras.getWidth(), lblAtras.getHeight(), Image.SCALE_DEFAULT));
       lblAtras.setIcon(icono6);
       this.repaint();
       
        ImageIcon imagen11 = new ImageIcon("src/Imagenes/descarga.jpg");
       Icon icono11 = new ImageIcon(imagen11.getImage().getScaledInstance( lblFondo.getWidth(), lblFondo.getHeight(), Image.SCALE_DEFAULT));
       lblFondo.setIcon(icono11);
       this.repaint();
       
        ImageIcon imagen3 = new ImageIcon("src/Imagenes/imprimir.png");
       Icon icono3 = new ImageIcon(imagen3.getImage().getScaledInstance( lblimprimir.getWidth(), lblimprimir.getHeight(), Image.SCALE_DEFAULT));
       lblimprimir.setIcon(icono3);
       this.repaint();
    }
    
    
    
    
    public String currentDate(){
    SimpleDateFormat d= new SimpleDateFormat("yyyy-MM-dd");
    Date now = new Date();
    String date= d.format(now);
    
    return date; 
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDayChooser1 = new com.toedter.calendar.JDayChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblEntrada = new javax.swing.JLabel();
        lblSalida = new javax.swing.JLabel();
        lblCabaña = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        lblISV = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblAtras = new javax.swing.JLabel();
        lblimprimir = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblVisitantes = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblRecargo = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        Factura = new javax.swing.JLabel();
        fecha_emision = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        fecha_emision1 = new javax.swing.JLabel();
        Factura1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Cambria Math", 1, 24)); // NOI18N
        jLabel1.setText("San Matias Resort");

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/descarga.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Cambria Math", 0, 10)); // NOI18N
        jLabel2.setText("Nombre del Cliente: ");
        jLabel2.setDoubleBuffered(true);

        jLabel3.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        jLabel3.setText("DNI:");
        jLabel3.setDoubleBuffered(true);

        jLabel4.setFont(new java.awt.Font("Cambria Math", 0, 10)); // NOI18N
        jLabel4.setText("Fecha de Entrada:");
        jLabel4.setDoubleBuffered(true);

        jLabel5.setFont(new java.awt.Font("Cambria Math", 0, 10)); // NOI18N
        jLabel5.setText("Fecha de Salida:");
        jLabel5.setDoubleBuffered(true);

        jLabel6.setFont(new java.awt.Font("Cambria Math", 0, 10)); // NOI18N
        jLabel6.setText("Cabaña:");
        jLabel6.setDoubleBuffered(true);

        jLabel7.setFont(new java.awt.Font("Cambria Math", 0, 10)); // NOI18N
        jLabel7.setText("Cantidad de Personas:");
        jLabel7.setDoubleBuffered(true);

        jLabel8.setFont(new java.awt.Font("Cambria Math", 0, 10)); // NOI18N
        jLabel8.setText("Precio por noche Cabaña:");
        jLabel8.setDoubleBuffered(true);

        jLabel10.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        jLabel10.setText("--------------------------------------------------------------");

        jLabel11.setFont(new java.awt.Font("Cambria Math", 0, 10)); // NOI18N
        jLabel11.setText("Subtotal:");
        jLabel11.setDoubleBuffered(true);

        jLabel12.setFont(new java.awt.Font("Cambria Math", 0, 10)); // NOI18N
        jLabel12.setText("ISV 15%");
        jLabel12.setDoubleBuffered(true);

        jLabel13.setFont(new java.awt.Font("Cambria Math", 0, 10)); // NOI18N
        jLabel13.setText("Total a Pagar:");
        jLabel13.setDoubleBuffered(true);

        jLabel14.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        jLabel14.setText("La Factura es beneficio de todos, Exigela!");

        lblNombre.setFont(new java.awt.Font("Cambria Math", 0, 10)); // NOI18N
        lblNombre.setText("jLabel16");

        lblID.setFont(new java.awt.Font("Cambria Math", 0, 10)); // NOI18N
        lblID.setText("jLabel17");

        lblEntrada.setFont(new java.awt.Font("Cambria Math", 0, 10)); // NOI18N
        lblEntrada.setText("jLabel18");

        lblSalida.setFont(new java.awt.Font("Cambria Math", 0, 10)); // NOI18N
        lblSalida.setText("jLabel19");

        lblCabaña.setFont(new java.awt.Font("Cambria Math", 0, 10)); // NOI18N
        lblCabaña.setText("jLabel20");

        lblCantidad.setFont(new java.awt.Font("Cambria Math", 0, 10)); // NOI18N
        lblCantidad.setText("jLabel21");

        lblPrecio.setFont(new java.awt.Font("Cambria Math", 0, 10)); // NOI18N
        lblPrecio.setText("jLabel22");

        lblSubtotal.setFont(new java.awt.Font("Cambria Math", 0, 10)); // NOI18N
        lblSubtotal.setText("jLabel24");

        lblISV.setFont(new java.awt.Font("Cambria Math", 0, 10)); // NOI18N
        lblISV.setText("jLabel25");

        lblTotal.setFont(new java.awt.Font("Cambria Math", 0, 10)); // NOI18N
        lblTotal.setText("jLabel26");

        lblAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha-hacia-atras.png"))); // NOI18N
        lblAtras.setText("jLabel15");
        lblAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAtrasMouseClicked(evt);
            }
        });

        lblimprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imprimir.png"))); // NOI18N
        lblimprimir.setText("jLabel27");
        lblimprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimprimirMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Cambria Math", 0, 10)); // NOI18N
        jLabel15.setText("Capacidad de personas :");
        jLabel15.setDoubleBuffered(true);

        lblVisitantes.setFont(new java.awt.Font("Cambria Math", 0, 10)); // NOI18N
        lblVisitantes.setText("jLabel16");

        jLabel16.setFont(new java.awt.Font("Cambria Math", 0, 10)); // NOI18N
        jLabel16.setText("RecargoxVisitantesExtras:");
        jLabel16.setDoubleBuffered(true);

        lblRecargo.setFont(new java.awt.Font("Cambria Math", 0, 10)); // NOI18N
        lblRecargo.setText("jLabel17");

        jLabel17.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        jLabel17.setText("CA-5-Norte Desvio contrario a Aqua Splash ");
        jLabel17.setDoubleBuffered(true);

        jLabel18.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        jLabel18.setText("sanmatiasresort08@gmail.com");
        jLabel18.setDoubleBuffered(true);

        jLabel19.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        jLabel19.setText("Tel. 9778-7070");
        jLabel19.setDoubleBuffered(true);

        jLabel20.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        jLabel20.setText("R.T.N: 0826192603360");
        jLabel20.setDoubleBuffered(true);

        jLabel21.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        jLabel21.setText("CAI:25050830152512");
        jLabel21.setDoubleBuffered(true);

        Factura.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        Factura.setText("No.Factura: ");
        Factura.setDoubleBuffered(true);

        fecha_emision.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        fecha_emision.setText("Fecha Emision: ");
        fecha_emision.setDoubleBuffered(true);

        jLabel24.setFont(new java.awt.Font("Cambria Math", 0, 10)); // NOI18N
        jLabel24.setText("Rango Autorizado: 0001-0002-01-000010000 a la 0002000");
        jLabel24.setDoubleBuffered(true);

        fecha_emision1.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        fecha_emision1.setText("Fecha Emision: ");
        fecha_emision1.setDoubleBuffered(true);

        Factura1.setFont(new java.awt.Font("Cambria Math", 0, 12)); // NOI18N
        Factura1.setText("FACTURA");
        Factura1.setDoubleBuffered(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel19))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel21)))
                                .addGap(29, 29, 29)
                                .addComponent(Factura))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(lblFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(Factura1))))
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(140, 140, 140))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel16))
                                .addGap(140, 140, 140)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(lblSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(lblEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCabaña, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVisitantes)
                            .addComponent(lblRecargo)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(fecha_emision1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fecha_emision)
                        .addGap(62, 62, 62)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(194, 194, 194)
                        .addComponent(jLabel11)))
                .addGap(142, 142, 142)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSubtotal)
                    .addComponent(lblISV)
                    .addComponent(lblTotal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addGap(48, 48, 48))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblimprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21)
                                    .addComponent(Factura)
                                    .addComponent(Factura1))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fecha_emision)
                                    .addComponent(fecha_emision1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(lblEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(lblSalida))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblCabaña, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblPrecio))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lblVisitantes))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblimprimir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(jLabel9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(lblRecargo))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(lblSubtotal))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(lblISV))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(lblTotal))))
                        .addGap(0, 161, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblimprimirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimprimirMouseClicked
      
        lblAtras.setVisible(true);
        lblimprimir.setVisible(false);
        try{
            PrinterJob gap= PrinterJob.getPrinterJob();
            gap.setPrintable(this);
            boolean top=gap.printDialog();
            if(top)
            {
                gap.print();
            }
            
        }catch(PrinterException pex){
            JOptionPane.showMessageDialog(null,"Error de Programa","Error\n"+pex, JOptionPane.INFORMATION_MESSAGE);
        }
        
        FacturacionR r= new FacturacionR();
        r.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblimprimirMouseClicked

    private void lblAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAtrasMouseClicked
        FacturacionR r= new FacturacionR();
        r.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblAtrasMouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Facturita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Facturita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Facturita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Facturita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Facturita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Factura;
    private javax.swing.JLabel Factura1;
    private javax.swing.JLabel fecha_emision;
    private javax.swing.JLabel fecha_emision1;
    private com.toedter.calendar.JDayChooser jDayChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAtras;
    private javax.swing.JLabel lblCabaña;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblEntrada;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblISV;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblRecargo;
    private javax.swing.JLabel lblSalida;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblVisitantes;
    private javax.swing.JLabel lblimprimir;
    // End of variables declaration//GEN-END:variables

 @Override
    public int print(Graphics graf, PageFormat pagfor, int index) throws PrinterException {
        if(index>0)
        {
            return NO_SUCH_PAGE;
        }
        Graphics2D hub=(Graphics2D) graf;
        hub.translate(pagfor.getImageableX()+30, pagfor.getImageableX()+30);
        hub.scale(0.5, 0.5);
        
     
        jPanel1.paintAll(graf);
        
        return PAGE_EXISTS;
    }

}
