/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sanmatiasresort;

import Clases.Conexion;
import Clases.Utilidades;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.util.Calendar;
import java.util.Date;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author 50489
 */
public class FacturacionR extends javax.swing.JFrame {

    PreparedStatement ps;
    ResultSet rs; 
    Conexion  con= new Conexion();
    Connection conn=con.conectar();
    int CabañaID; 
    final float CostoExtra=200;
    float precio;
    int capacidad;
    float subtotal;
    String codigo;
    iniciosesion is=new iniciosesion();
    Utilidades util = new Utilidades();
    public FacturacionR() {
        initComponents();
        NoHabilitarInsertOnly();
         cmbcabaña.setModel(con.obtenerCabaña());
    }
    
    public void HabilitarInsertOnly(){
        btnreservar.setEnabled(true);
        btngenerarfactura.setEnabled(true);
    }
     public void NoHabilitarInsertOnly(){
        btnreservar.setEnabled(false);
        btngenerarfactura.setEnabled(false);
    }
     
      public static String ID="";
    public static String NOMBRE="";
    public static String CABANA="";
    public static String ENTRADA="";
    public static String SALIDA="";
    public static String CANTIDAD="";
    public static String PRECIO="";
    public static String RECARGO="";
    public static String SUBTOTAL="";
    public static String TOTAL="";
    public static String VISITANTES="";
    public static String Factura="";
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblfacturacion = new javax.swing.JLabel();
        lbldnicliente = new javax.swing.JLabel();
        txtdnicliente = new javax.swing.JTextField();
        lblcabaña = new javax.swing.JLabel();
        cmbcabaña = new javax.swing.JComboBox<>();
        lblcantidadpersonasfactura = new javax.swing.JLabel();
        txtcantidadpersonasfactura = new javax.swing.JTextField();
        lbldiallegada = new javax.swing.JLabel();
        lbldiasalida = new javax.swing.JLabel();
        jdchooser = new com.toedter.calendar.JDateChooser();
        jdchooser2 = new com.toedter.calendar.JDateChooser();
        btnverificarfactura1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        personaextra = new javax.swing.JTextField();
        costoextra = new javax.swing.JTextField();
        subtotal1 = new javax.swing.JTextField();
        isv1 = new javax.swing.JTextField();
        total1 = new javax.swing.JTextField();
        btnvolverreservacion = new javax.swing.JButton();
        btnreservar = new javax.swing.JButton();
        btngenerarfactura = new javax.swing.JButton();
        lbltipopagofactura = new javax.swing.JLabel();
        cmbtipopago = new javax.swing.JComboBox<>();
        lbldnierror = new javax.swing.JLabel();
        lbldnierror1 = new javax.swing.JLabel();
        lblerror2 = new javax.swing.JLabel();
        btngenerarfactura1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(33, 126, 194));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblfacturacion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblfacturacion.setText("FACTURACIÓN/RESERVACIÓN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblfacturacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(451, 451, 451))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblfacturacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        lbldnicliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbldnicliente.setForeground(new java.awt.Color(255, 255, 255));
        lbldnicliente.setText("DNI Cliente");

        txtdnicliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdniclienteKeyTyped(evt);
            }
        });

        lblcabaña.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblcabaña.setForeground(new java.awt.Color(255, 255, 255));
        lblcabaña.setText("Cabaña");

        cmbcabaña.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbcabaña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbcabañaMouseClicked(evt);
            }
        });

        lblcantidadpersonasfactura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblcantidadpersonasfactura.setForeground(new java.awt.Color(255, 255, 255));
        lblcantidadpersonasfactura.setText("Cantidad de Personas");

        txtcantidadpersonasfactura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcantidadpersonasfacturaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcantidadpersonasfacturaKeyTyped(evt);
            }
        });

        lbldiallegada.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbldiallegada.setForeground(new java.awt.Color(255, 255, 255));
        lbldiallegada.setText("Dia de Llegada");

        lbldiasalida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbldiasalida.setForeground(new java.awt.Color(255, 255, 255));
        lbldiasalida.setText("Dia de Salida");

        jdchooser.setDateFormatString("yyyy-MM-dd");
        jdchooser.setMaxSelectableDate(new Date());
        jdchooser.setMinSelectableDate(new Date());
        jdchooser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jdchooserMouseClicked(evt);
            }
        });

        jdchooser2.setDateFormatString("yyyy-MM-dd");
        jdchooser2.setMinSelectableDate(new Date());

        btnverificarfactura1.setBackground(new java.awt.Color(30, 150, 56));
        btnverificarfactura1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnverificarfactura1.setForeground(new java.awt.Color(255, 255, 255));
        btnverificarfactura1.setText("Verificar");
        btnverificarfactura1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnverificarfactura1MouseClicked(evt);
            }
        });
        btnverificarfactura1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverificarfactura1ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalles", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Personas Extras");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Costos Extras");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Subtotal");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("ISV");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Total");

        personaextra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        personaextra.setEnabled(false);
        personaextra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personaextraActionPerformed(evt);
            }
        });

        costoextra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        costoextra.setEnabled(false);
        costoextra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                costoextraActionPerformed(evt);
            }
        });

        subtotal1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        subtotal1.setEnabled(false);
        subtotal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtotal1ActionPerformed(evt);
            }
        });

        isv1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        isv1.setEnabled(false);
        isv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isv1ActionPerformed(evt);
            }
        });

        total1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        total1.setEnabled(false);
        total1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(total1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isv1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subtotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(costoextra, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(personaextra, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(personaextra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(costoextra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(subtotal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(isv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(total1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnvolverreservacion.setBackground(new java.awt.Color(230, 203, 1));
        btnvolverreservacion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnvolverreservacion.setForeground(new java.awt.Color(255, 255, 255));
        btnvolverreservacion.setText("Volver");
        btnvolverreservacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnvolverreservacionMouseClicked(evt);
            }
        });
        btnvolverreservacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverreservacionActionPerformed(evt);
            }
        });

        btnreservar.setBackground(new java.awt.Color(62, 61, 86));
        btnreservar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnreservar.setForeground(new java.awt.Color(255, 255, 255));
        btnreservar.setText("RESERVAR");
        btnreservar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnreservarMouseClicked(evt);
            }
        });

        btngenerarfactura.setBackground(new java.awt.Color(221, 159, 0));
        btngenerarfactura.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btngenerarfactura.setForeground(new java.awt.Color(255, 255, 255));
        btngenerarfactura.setText("GENERAR FACTURA");
        btngenerarfactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btngenerarfacturaMouseClicked(evt);
            }
        });

        lbltipopagofactura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbltipopagofactura.setForeground(new java.awt.Color(255, 255, 255));
        lbltipopagofactura.setText("Tipo de Pago");

        cmbtipopago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el tipo de pago ", "Eféctivo", "Cheque", "Crédito" }));

        lbldnierror.setForeground(new java.awt.Color(255, 0, 51));

        lbldnierror1.setForeground(new java.awt.Color(255, 0, 51));

        lblerror2.setForeground(new java.awt.Color(255, 0, 51));

        btngenerarfactura1.setBackground(new java.awt.Color(221, 159, 0));
        btngenerarfactura1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btngenerarfactura1.setForeground(new java.awt.Color(255, 255, 255));
        btngenerarfactura1.setText("LIMPIAR DATOS");
        btngenerarfactura1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btngenerarfactura1MouseClicked(evt);
            }
        });
        btngenerarfactura1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngenerarfactura1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cmbtipopago, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblcabaña, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblcantidadpersonasfactura, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(cmbcabaña, javax.swing.GroupLayout.Alignment.LEADING, 0, 232, Short.MAX_VALUE)
                                        .addComponent(lbldnierror, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                        .addComponent(txtcantidadpersonasfactura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                        .addComponent(lbldnierror1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbldiallegada, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addComponent(lbldiasalida, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnreservar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btngenerarfactura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblerror2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbltipopagofactura, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jdchooser, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jdchooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnverificarfactura1)
                                .addGap(209, 209, 209)
                                .addComponent(btngenerarfactura1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnvolverreservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lbldnicliente, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 639, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txtdnicliente, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(520, Short.MAX_VALUE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnreservar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btngenerarfactura, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbldnierror, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblcabaña)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbcabaña, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblcantidadpersonasfactura)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtcantidadpersonasfactura, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(lbldnierror1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbldiallegada)
                            .addComponent(lbldiasalida))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdchooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jdchooser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnverificarfactura1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btngenerarfactura1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addComponent(lbltipopagofactura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbtipopago, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(btnvolverreservacion)
                .addGap(295, 295, 295)
                .addComponent(lblerror2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(64, 64, 64)
                    .addComponent(lbldnicliente, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(13, 13, 13)
                    .addComponent(txtdnicliente, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(842, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 741, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdniclienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdniclienteKeyTyped
        if(!Character.isDigit(evt.getKeyChar())&&!(evt.getKeyChar() == KeyEvent.VK_SPACE)){
            evt.consume();
            lbldnierror.setText("El campo no admite letras");
        }else{
            lbldnierror.setText("");
        }

        if(txtdnicliente.getText().length()==13){
            evt.consume();
        }

    }//GEN-LAST:event_txtdniclienteKeyTyped
    
    
    public int diasEstadia(Date fecha_e, Date  fecha_s){
    int estadia=0;
    LocalDate fecha = fecha_e.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
    LocalDate fecha2=fecha_s.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
    LocalDate date1= LocalDate.of(fecha.getYear(),fecha.getMonth(),fecha.getDayOfMonth());
    LocalDate date2 = LocalDate.of(fecha2.getYear(), fecha2.getMonth(), fecha2.getDayOfMonth());
    
    
    Period periodo = Period.between(date2,date1);
    estadia=Math.abs(periodo.getDays());
    return estadia;
    }
    public void LimpiarDatos(){
    txtdnicliente.setText("");
    txtcantidadpersonasfactura.setText("");
    cmbcabaña.setSelectedIndex(0);
    cmbtipopago.setSelectedIndex(0);
    personaextra.setText("");
    costoextra.setText("");
    subtotal1.setText("");
    isv1.setText("");
    total1.setText("");
    }
    
    private void txtcantidadpersonasfacturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidadpersonasfacturaKeyTyped
        if(!(Character.isDigit(evt.getKeyChar())&& !(evt.getKeyChar()==KeyEvent.VK_SPACE))){
            evt.consume();
            lbldnierror1.setText("El campo no admite letras");
        }else{
            lbldnierror1.setText("");}
    }//GEN-LAST:event_txtcantidadpersonasfacturaKeyTyped

    private void jdchooserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdchooserMouseClicked

    }//GEN-LAST:event_jdchooserMouseClicked

    private void btnverificarfactura1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnverificarfactura1MouseClicked
        try {
            ps=conn.prepareStatement("Select  codigo_cabaña from cabañas where descripcion_cabaña=?");
            ps.setString(1,cmbcabaña.getSelectedItem().toString());
            rs=ps.executeQuery();
            while(rs.next()){
                CabañaID=rs.getInt(1);

            }
            ps=conn.prepareStatement("select A.codigo_reservacion from reservaciones as A  join detalle_reservaciones as B on A.codigo_reservacion=B.codigo_reservacion \n" +
            "WHERE B.codigo_cabaña=? AND A.fecha_llegada=? AND A.fecha_salida=? AND A.fecha_llegada between ? AND  ? AND A.fecha_salida between ? and ?");
            ps.setInt(1,CabañaID);
            ps.setString(2,((JTextField)jdchooser.getDateEditor().getUiComponent()).getText());
            ps.setString(3,((JTextField)jdchooser.getDateEditor().getUiComponent()).getText());
            ps.setString(4,((JTextField)jdchooser.getDateEditor().getUiComponent()).getText());
            ps.setString(5,((JTextField)jdchooser.getDateEditor().getUiComponent()).getText());
            ps.setString(6,((JTextField)jdchooser.getDateEditor().getUiComponent()).getText());
            ps.setString(7,((JTextField)jdchooser.getDateEditor().getUiComponent()).getText());
            rs=ps.executeQuery();
            if(rs.next()){
                System.out.println(CabañaID);
                System.out.println(rs.getString(1));
                
                    JOptionPane.showMessageDialog(null, "La cabaña esta reservada este tiempo");
                
            }else{
             JOptionPane.showMessageDialog(null,"La cabaña esta libre");
                    HabilitarInsertOnly();
            }

                // TODO add your handling code here:
            } catch (SQLException ex) {
                Logger.getLogger(FacturacionR.class.getName()).log(Level.SEVERE, null, ex);
            }
         try {
            ps=conn.prepareStatement("Select capacidad_cabaña, codigo_cabaña,precio_cabaña from cabañas where descripcion_cabaña=?");
           ps.setString(1,cmbcabaña.getSelectedItem().toString());
            rs=ps.executeQuery();
            while(rs.next()){
             CabañaID=rs.getInt(2);
             precio=rs.getFloat(3);
             capacidad=rs.getInt(1);
               }
            int cantidadpersonas=Integer.parseInt(txtcantidadpersonasfactura.getText());
           if((cantidadpersonas-capacidad)<0){
               personaextra.setText(String.valueOf(0));
           }else{
              personaextra.setText(String.valueOf(cantidadpersonas-capacidad)); 
           }
           float costo=Integer.parseInt(personaextra.getText())*CostoExtra;
           float subtotal=(diasEstadia(jdchooser.getDate(),jdchooser2.getDate())*precio)+costo;
           float isv =(float) (subtotal*0.15);
           float total=subtotal+isv;
           costoextra.setText(String.valueOf(costo));
           subtotal1.setText(String.valueOf(subtotal));
           isv1.setText(String.valueOf(isv));
           total1.setText(String.valueOf(total));
           
           
            
        } catch (SQLException ex) {
            Logger.getLogger(FacturacionR.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }//GEN-LAST:event_btnverificarfactura1MouseClicked

    private void btnverificarfactura1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverificarfactura1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnverificarfactura1ActionPerformed

    private void btnvolverreservacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnvolverreservacionMouseClicked
        menu m=new menu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnvolverreservacionMouseClicked

    private void btnvolverreservacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverreservacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnvolverreservacionActionPerformed

    private void personaextraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personaextraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personaextraActionPerformed

    private void costoextraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_costoextraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_costoextraActionPerformed

    private void subtotal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtotal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subtotal1ActionPerformed

    private void isv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isv1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isv1ActionPerformed

    private void total1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total1ActionPerformed

    private void btnreservarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnreservarMouseClicked
 if(txtdnicliente.getText().isEmpty() || cmbcabaña.getSelectedIndex()==0 || txtcantidadpersonasfactura.getText().isEmpty() || cmbtipopago.getSelectedIndex()==0){
 JOptionPane.showMessageDialog(null, "Todos los campos deben de estar llenos");
 }else{
        codigo= UUID.randomUUID().toString();
         try{
              int codigoCID=0; 
                ps=conn.prepareStatement("Select codigo_cliente from clientes where dni_cliente=?");
               ps.setString(1,txtdnicliente.getText());
               rs=ps.executeQuery();
               while(rs.next()){
                   codigoCID=rs.getInt(1);
               }
               
               if(Integer.parseInt(txtcantidadpersonasfactura.getText())==0){
               
               }
               ps=conn.prepareStatement("call sanmatiasresort.INSERT_RESERVATIONS(?,?,?,?,?,?,?,?,?,?);");
               ps.setInt(1,is.empleado);
               ps.setInt(2, codigoCID);
               ps.setString(3,((JTextField)jdchooser.getDateEditor().getUiComponent()).getText());
               ps.setString(4,((JTextField)jdchooser2.getDateEditor().getUiComponent()).getText());
               ps.setInt(5,cmbtipopago.getSelectedIndex());
               ps.setInt(6, CabañaID);
               ps.setInt(7,Integer.parseInt(txtcantidadpersonasfactura.getText()));     
               ps.setFloat(8,Float.parseFloat(costoextra.getText()));
               ps.setFloat(9,precio);
               ps.setString(10,codigo);
                String pregunta=util.strPreguntaSiNo("Desea agregar la reservación");
                if(pregunta=="Si"){
                ps.executeUpdate();
                btnreservar.setEnabled(true);
                btngenerarfactura.setEnabled(true);
              
               
                
                JOptionPane.showMessageDialog(null, "Registro de datos exitosa");
                
                }
               
               
               
           } catch (SQLException ex) {
               Logger.getLogger(FacturacionR.class.getName()).log(Level.SEVERE, null, ex);
           }
        
 } 
    }//GEN-LAST:event_btnreservarMouseClicked

    private void txtcantidadpersonasfacturaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidadpersonasfacturaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidadpersonasfacturaKeyReleased

    private void cmbcabañaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbcabañaMouseClicked


        // TODO add your handling code here:
    }//GEN-LAST:event_cmbcabañaMouseClicked

    private void btngenerarfacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btngenerarfacturaMouseClicked
       
            ID=txtdnicliente.getText();
            CABANA=cmbcabaña.getSelectedItem().toString();
            ENTRADA=String.valueOf(jdchooser.getDate());
            SALIDA=String.valueOf(jdchooser2.getDate());
            PRECIO=String.valueOf(precio);
            CANTIDAD=txtcantidadpersonasfactura.getText();
            SUBTOTAL=subtotal1.getText();
            TOTAL=total1.getText();
            VISITANTES=personaextra.getText();
            Factura=codigo;
            try {
            ps = conn.prepareStatement("select nombre_cliente from clientes where dni_cliente = ?");
            ps.setString(1, txtdnicliente.getText());
            rs = ps.executeQuery();
            
            while(rs.next()){
                NOMBRE= rs.getString("nombre_cliente");
            }} catch (SQLException ex) {
            Logger.getLogger(FacturacionR.class.getName()).log(Level.SEVERE, null, ex);
        }
            if (Integer.parseInt(txtcantidadpersonasfactura.getText())>capacidad){
                RECARGO= costoextra.getText();
            }else{
                RECARGO="0";
            }
            Facturita factura = new Facturita();
            factura.setVisible(true);
            this.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_btngenerarfacturaMouseClicked

    private void btngenerarfactura1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btngenerarfactura1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btngenerarfactura1MouseClicked

    private void btngenerarfactura1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngenerarfactura1ActionPerformed
       LimpiarDatos();
        // TODO add your handling code here:
    }//GEN-LAST:event_btngenerarfactura1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacturacionR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacturacionR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacturacionR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacturacionR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacturacionR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btngenerarfactura;
    private javax.swing.JButton btngenerarfactura1;
    private javax.swing.JButton btnreservar;
    private javax.swing.JButton btnverificarfactura1;
    private javax.swing.JButton btnvolverreservacion;
    private javax.swing.JComboBox<String> cmbcabaña;
    private javax.swing.JComboBox<String> cmbtipopago;
    private javax.swing.JTextField costoextra;
    private javax.swing.JTextField isv1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private com.toedter.calendar.JDateChooser jdchooser;
    private com.toedter.calendar.JDateChooser jdchooser2;
    private javax.swing.JLabel lblcabaña;
    private javax.swing.JLabel lblcantidadpersonasfactura;
    private javax.swing.JLabel lbldiallegada;
    private javax.swing.JLabel lbldiasalida;
    private javax.swing.JLabel lbldnicliente;
    private javax.swing.JLabel lbldnierror;
    private javax.swing.JLabel lbldnierror1;
    private javax.swing.JLabel lblerror2;
    private javax.swing.JLabel lblfacturacion;
    private javax.swing.JLabel lbltipopagofactura;
    private javax.swing.JTextField personaextra;
    private javax.swing.JTextField subtotal1;
    private javax.swing.JTextField total1;
    private javax.swing.JTextField txtcantidadpersonasfactura;
    private javax.swing.JTextField txtdnicliente;
    // End of variables declaration//GEN-END:variables
}
