/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sanmatiasresort;

import Clases.Conexion;
import Clases.CryptContra;
import Clases.Utilidades;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author 50489
 */
public class recuperacioncontra extends javax.swing.JFrame {
    String warning1="",warning2="",warning3="";
    Conexion conn=new Conexion();
    Connection con=conn.conectar();
    PreparedStatement ps;
    ResultSet rs;
    Utilidades utilities= new Utilidades();
    CryptContra crypt=new CryptContra();
    /**
     * Creates new form recuperacioncontra
     */
    public recuperacioncontra() {
        initComponents();
        txtusuarior.grabFocus();
    }
    public void limpiarDatos(){
    txtusuarior.setText("");
    txtnuevacontrasena.setText("");
    txtconfirmacioncontrasena.setText("");
    lblisvalid.setText("");
    txtadvertencia.setText("");
    txtusuarior.grabFocus();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblempleados = new javax.swing.JLabel();
        lblnombreempleado1 = new javax.swing.JLabel();
        txtusuarior = new javax.swing.JTextField();
        lblnombreempleado2 = new javax.swing.JLabel();
        lblnombreempleado3 = new javax.swing.JLabel();
        txtconfirmacioncontrasena = new javax.swing.JPasswordField();
        txtnuevacontrasena = new javax.swing.JPasswordField();
        txtadvertencia = new javax.swing.JLabel();
        lblisvalid = new javax.swing.JLabel();
        btnconfirmar = new javax.swing.JButton();
        btnvolver = new javax.swing.JButton();
        lblusuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Recuperación de Contraseña");
        setBackground(new java.awt.Color(33, 126, 194));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(33, 126, 194));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logocirculo.png"))); // NOI18N

        lblempleados.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblempleados.setForeground(new java.awt.Color(255, 255, 255));
        lblempleados.setText("RECUPERACIÓN DE CONTRASEÑA");

        lblnombreempleado1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblnombreempleado1.setForeground(new java.awt.Color(255, 255, 255));
        lblnombreempleado1.setText("Nueva Contraseña");

        txtusuarior.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtusuariorKeyTyped(evt);
            }
        });

        lblnombreempleado2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblnombreempleado2.setForeground(new java.awt.Color(255, 255, 255));
        lblnombreempleado2.setText("Usuario");

        lblnombreempleado3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblnombreempleado3.setForeground(new java.awt.Color(255, 255, 255));
        lblnombreempleado3.setText("Confirmar Contraseña");

        txtconfirmacioncontrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtconfirmacioncontrasenaKeyTyped(evt);
            }
        });

        txtnuevacontrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnuevacontrasenaKeyTyped(evt);
            }
        });

        txtadvertencia.setForeground(new java.awt.Color(255, 51, 51));

        lblisvalid.setForeground(new java.awt.Color(255, 102, 102));

        btnconfirmar.setBackground(new java.awt.Color(30, 150, 56));
        btnconfirmar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnconfirmar.setForeground(new java.awt.Color(255, 255, 255));
        btnconfirmar.setText("Confirmar");
        btnconfirmar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnconfirmarMouseClicked(evt);
            }
        });
        btnconfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfirmarActionPerformed(evt);
            }
        });

        btnvolver.setBackground(new java.awt.Color(230, 203, 1));
        btnvolver.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnvolver.setForeground(new java.awt.Color(255, 255, 255));
        btnvolver.setText("Volver");
        btnvolver.setToolTipText("");
        btnvolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnvolverMouseClicked(evt);
            }
        });
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });

        lblusuario.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblempleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtadvertencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(103, 103, 103))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblnombreempleado2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(232, 232, 232))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblnombreempleado3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblisvalid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(120, 120, 120))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtconfirmacioncontrasena)
                                .addGap(213, 213, 213)))
                        .addGap(82, 82, 82))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtnuevacontrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnconfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addGap(66, 66, 66)
                        .addComponent(btnvolver, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                        .addGap(158, 158, 158))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtusuarior, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblnombreempleado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(lblempleados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblnombreempleado2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtusuarior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblnombreempleado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtnuevacontrasena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtadvertencia, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblnombreempleado3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtconfirmacioncontrasena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblisvalid, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnconfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnvolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnconfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnconfirmarActionPerformed

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnvolverActionPerformed

    private void btnvolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnvolverMouseClicked
       iniciosesion is =new iniciosesion();
       is.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btnvolverMouseClicked

    private void txtnuevacontrasenaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnuevacontrasenaKeyTyped
      String password=txtnuevacontrasena.getText().toString();
      
        if(utilities.isPasswordValid(password)){
             warning1="";
            txtadvertencia.setText(warning1);
            
        }else{
             warning1="La contraseña debe de contenter: 3 Mayus, 2 numeros";
            txtadvertencia.setText(warning1);
        }
        
         if(txtnuevacontrasena.getText().length()==10){
            evt.consume();
        }
    }//GEN-LAST:event_txtnuevacontrasenaKeyTyped

    private void txtconfirmacioncontrasenaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtconfirmacioncontrasenaKeyTyped
      
      if(txtconfirmacioncontrasena.getText().length()==12){
            evt.consume();
        }
    }//GEN-LAST:event_txtconfirmacioncontrasenaKeyTyped

    private void txtusuariorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusuariorKeyTyped
       if(txtusuarior.getText().isEmpty()){
           warning3="No se puede dejar el espacio en blanco";
           lblusuario.setText(warning3);
       } else{
           warning3="";
           lblusuario.setText(warning3);
       }
       
    }//GEN-LAST:event_txtusuariorKeyTyped

    private void btnconfirmarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnconfirmarMouseClicked
        if(txtusuarior.getText().isEmpty() || txtnuevacontrasena.getText().isEmpty() || txtconfirmacioncontrasena.getText().isEmpty()){
        String hashedpassword= crypt.DIGESTION(txtnuevacontrasena.getText());
     String strRespuesta;
        if(warning1.isEmpty()&& warning2.isEmpty() && warning3.isEmpty()){
         JOptionPane.showMessageDialog(this,"Asegurese de ingresar correctamente los datos");
     }else{
         try {
             ps=con.prepareStatement("call sanmatiasresort.UPDATE_USUARIO(?, ?, ?);");
             ps.setString(1,txtusuarior.getText());
             ps.setString(2, hashedpassword);
             ps.setString(3, "ACT");
             strRespuesta=utilities.strPreguntaSiNo("Esta Seguro de que se realiazara el cambio");
             if(strRespuesta=="Si"){
             ps.executeUpdate();
             JOptionPane.showMessageDialog(null,"Se Modificaron los datos exitosamente");
             limpiarDatos();
             }else{
             JOptionPane.showMessageDialog(null,"Oh oh algo paso");
             limpiarDatos();
             }
         } catch (SQLException ex) {
             Logger.getLogger(recuperacioncontra.class.getName()).log(Level.SEVERE, null, ex);
         }
     }
        }else{
                     JOptionPane.showMessageDialog(this,"Verifique que no hayan campos vacios");
                
                }
    }//GEN-LAST:event_btnconfirmarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(recuperacioncontra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(recuperacioncontra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(recuperacioncontra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(recuperacioncontra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new recuperacioncontra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconfirmar;
    private javax.swing.JButton btnvolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblempleados;
    private javax.swing.JLabel lblisvalid;
    private javax.swing.JLabel lblnombreempleado1;
    private javax.swing.JLabel lblnombreempleado2;
    private javax.swing.JLabel lblnombreempleado3;
    private javax.swing.JLabel lblusuario;
    private javax.swing.JLabel txtadvertencia;
    private javax.swing.JPasswordField txtconfirmacioncontrasena;
    private javax.swing.JPasswordField txtnuevacontrasena;
    private javax.swing.JTextField txtusuarior;
    // End of variables declaration//GEN-END:variables
}
