/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sanmatiasresort;

/**
 *
 * @author Juanfer Siu
 */
public class seguridad extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public seguridad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        panelprincipal = new javax.swing.JPanel();
        lblSeguridad = new javax.swing.JLabel();
        btnregistros = new javax.swing.JButton();
        btnvolverseguridad = new javax.swing.JButton();
        btnusuarios = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnregistros1 = new javax.swing.JButton();
        btnregistros2 = new javax.swing.JButton();
        btnregistros3 = new javax.swing.JButton();
        btnregistros4 = new javax.swing.JButton();
        btnregistros5 = new javax.swing.JButton();

        jButton5.setText("Reservación");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setBackground(new java.awt.Color(33, 126, 194));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 932, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelprincipal.setBackground(new java.awt.Color(33, 126, 194));
        panelprincipal.setForeground(new java.awt.Color(33, 126, 194));

        lblSeguridad.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblSeguridad.setForeground(new java.awt.Color(255, 255, 255));
        lblSeguridad.setText("SEGURIDAD");

        btnregistros.setBackground(new java.awt.Color(28, 151, 48));
        btnregistros.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnregistros.setForeground(new java.awt.Color(255, 255, 255));
        btnregistros.setText("Bitacora Acceso");
        btnregistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrosActionPerformed(evt);
            }
        });

        btnvolverseguridad.setBackground(new java.awt.Color(225, 198, 4));
        btnvolverseguridad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnvolverseguridad.setForeground(new java.awt.Color(255, 255, 255));
        btnvolverseguridad.setText("Volver");
        btnvolverseguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverseguridadActionPerformed(evt);
            }
        });

        btnusuarios.setBackground(new java.awt.Color(28, 151, 48));
        btnusuarios.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnusuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnusuarios.setText("Usuarios");
        btnusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnusuariosActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo.png"))); // NOI18N

        btnregistros1.setBackground(new java.awt.Color(28, 151, 48));
        btnregistros1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnregistros1.setForeground(new java.awt.Color(255, 255, 255));
        btnregistros1.setText("Bitacora Empleado");
        btnregistros1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistros1ActionPerformed(evt);
            }
        });

        btnregistros2.setBackground(new java.awt.Color(28, 151, 48));
        btnregistros2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnregistros2.setForeground(new java.awt.Color(255, 255, 255));
        btnregistros2.setText("Bitacora Usuarios");
        btnregistros2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistros2ActionPerformed(evt);
            }
        });

        btnregistros3.setBackground(new java.awt.Color(28, 151, 48));
        btnregistros3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnregistros3.setForeground(new java.awt.Color(255, 255, 255));
        btnregistros3.setText("Bitacora Cabañas");
        btnregistros3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistros3ActionPerformed(evt);
            }
        });

        btnregistros4.setBackground(new java.awt.Color(28, 151, 48));
        btnregistros4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnregistros4.setForeground(new java.awt.Color(255, 255, 255));
        btnregistros4.setText("Bitacora Reservaciones");
        btnregistros4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnregistros4MouseClicked(evt);
            }
        });
        btnregistros4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistros4ActionPerformed(evt);
            }
        });

        btnregistros5.setBackground(new java.awt.Color(28, 151, 48));
        btnregistros5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btnregistros5.setForeground(new java.awt.Color(255, 255, 255));
        btnregistros5.setText("Bitacora Cotización");
        btnregistros5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistros5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelprincipalLayout = new javax.swing.GroupLayout(panelprincipal);
        panelprincipal.setLayout(panelprincipalLayout);
        panelprincipalLayout.setHorizontalGroup(
            panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelprincipalLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 474, Short.MAX_VALUE)
                .addGroup(panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelprincipalLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnregistros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnusuarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelprincipalLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(lblSeguridad, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                .addGap(56, 56, 56))
                            .addComponent(btnregistros1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnregistros2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnregistros3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnregistros4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnregistros5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelprincipalLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnvolverseguridad, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(139, 139, 139))))
        );
        panelprincipalLayout.setVerticalGroup(
            panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelprincipalLayout.createSequentialGroup()
                .addGroup(panelprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelprincipalLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(lblSeguridad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnregistros, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnregistros1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnregistros3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnregistros2)
                        .addGap(14, 14, 14)
                        .addComponent(btnregistros5)
                        .addGap(18, 18, 18)
                        .addComponent(btnregistros4)
                        .addGap(28, 28, 28)
                        .addComponent(btnvolverseguridad, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 30, Short.MAX_VALUE))
            .addComponent(panelprincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelprincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnusuariosActionPerformed
       usuarios USU = new usuarios();
       USU.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnusuariosActionPerformed

    private void btnregistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrosActionPerformed
       bitacoras BIT = new bitacoras();
       BIT.setVisible(true);
       this.dispose();

    }//GEN-LAST:event_btnregistrosActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnvolverseguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverseguridadActionPerformed
       menu MEN = new menu();
       MEN.setVisible(true);
       this.dispose();

    }//GEN-LAST:event_btnvolverseguridadActionPerformed

    private void btnregistros1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistros1ActionPerformed
        bitacorasEmpleado bE = new bitacorasEmpleado();
        bE.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnregistros1ActionPerformed

    private void btnregistros2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistros2ActionPerformed
        bitacorasUsuario bu= new bitacorasUsuario();
        bu.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnregistros2ActionPerformed

    private void btnregistros3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistros3ActionPerformed
bitacorasCabañas bc= new bitacorasCabañas();
bc.setVisible(true);
this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnregistros3ActionPerformed

    private void btnregistros4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistros4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnregistros4ActionPerformed

    private void btnregistros5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistros5ActionPerformed
        bitacorasCotizacion bc= new bitacorasCotizacion();
        bc.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnregistros5ActionPerformed

    private void btnregistros4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnregistros4MouseClicked
        bitacorasReservacion br= new bitacorasReservacion();
        br.setVisible(true);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnregistros4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seguridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seguridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seguridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seguridad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new seguridad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnregistros;
    private javax.swing.JButton btnregistros1;
    private javax.swing.JButton btnregistros2;
    private javax.swing.JButton btnregistros3;
    private javax.swing.JButton btnregistros4;
    private javax.swing.JButton btnregistros5;
    private javax.swing.JButton btnusuarios;
    private javax.swing.JButton btnvolverseguridad;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblSeguridad;
    private javax.swing.JPanel panelprincipal;
    // End of variables declaration//GEN-END:variables
}
